### ISSUE TITLE
"Servers" box does not check for server address validity

### ISSUE THREAD

**Issue by veox** [darkwallet/darkwallet#55]
It is possible to enter an invalid `IP:Port` combination that will be added to the Servers list. Connecting to such a server will fail without a visible warning (popup), the interface continues displaying (e.g.):

```
Connecting to unsystem testnet 99091 @ wss://85.25.198.97:99091
```

There is a DOMException in the page console:

```
message: "Failed to construct 'WebSocket': The URL 'wss://85.25.198.97:99091/' is invalid."
name: "SyntaxError"
stack: "Error: Failed to construct 'WebSocket': The URL 'wss://85.25.198.97:99091/' is invalid.↵    at Error (native)↵    at new GatewayClient (chrome-extension://iggmmhbejghkcfmngickghjnhogfkili/vendors/darkwallet_gateway/client/gateway.js:15:22)↵    at ObeliskService.connectClient (chrome-extension://iggmmhbejghkcfmngickghjnhogfkili/js/backend/services/obelisk.js:95:21)↵    at ObeliskService.connect (chrome-extension://iggmmhbejghkcfmngickghjnhogfkili/js/backend/services/obelisk.js:45:16)↵    at DarkWalletService.connect (chrome-extension://iggmmhbejghkcfmngickghjnhogfkili/js/backend/main.js:68:26)↵    at window.connect (chrome-extension://iggmmhbejghkcfmngickghjnhogfkili/js/backend/main.js:151:53)↵    at h.$scope.connectServer (chrome-extension://iggmmhbejghkcfmngickghjnhogfkili/js/frontend/controllers/servers.js:82:23)↵    at chrome-extension://iggmmhbejghkcfmngickghjnhogfkili/vendors/angular/angular.min.js:172:382↵    at chrome-extension://iggmmhbejghkcfmngickghjnhogfkili/vendors/angular/angular.min.js:189:390↵    at h.$eval (chrome-extension://iggmmhbejghkcfmngickghjnhogfkili/vendors/angular/angular.min.js:108:482)"
```

Trying to connect to any other server after this will fail - extension developer console will show

```
[main] connecting ws://85.25.198.97:8888
```

but nothing else.

The rest of the wallet seems to remain functional, but since I can't connect to a testnet server anyway, cannot say if it truly is.

Using `darkwallet 0.1.0-2-gc89a638` with `chromium 34.0.1847.132 (265804)`.

**Comment by caedesvvv** [comment]
it's already in priority list on TODO
